version: "3.3"

services:
 mongodb:
   image: mongo:latest
   container_name: mongodb
   environment:
    MONGO_INITDB_ROOT_USERNAME: 
    MONGO_INITDB_ROOT_PASSWORD: 
   ports:
    - 27017:27017
   volumes:
    - .dbmongodb:/var/lib/lib/mongodb